### ISSUE TITLE
 Error in MutSig_2CV_v3_11_core (line 308)

### ISSUE THREAD

**Issue by amootta** [getzlab/MutSig2CV#5]
Hi, 
I'm running MutSig2CV on a MAF file generated from funcotator. I did not add any additional parameters in my run.  The MAF contains filtered mutations from just a single patient. However I received an error: 

WARNING:  MutSig is not applicable to single patients.
Imputing callschemes
Error using *
Inner matrix dimensions must agree.

Error in MutSig_2CV_v3_11_core (line 308)

Error in MutSig_2CV_v3_11_wrapper (line 50)

MATLAB:innerdim

Could you please let me know how I could fix this? Thanks very much

**Comment by julianhess** [comment]
Hi,

MutSig finds significant genes by looking for recurrent mutations across a cohort, i.e. multiple patients. As the warning indicates, it by definition cannot run on a single patient. You need to give it a MAF from a cohort consisting of multiple patients.

It may be more helpful to throw an error (rather than a warning) and quit at the single patient message, rather than continuing on to the cryptic error you're seeing.

—Julian
